apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: dhananjay/node-app-batch-6
      ports:
        - containerPort: 8000
